namePrefix: production-

commonLabels:
  env: production
  org: newrelic

commonAnnotations:
  env: production

configMapGenerator:
  - name: env-config
    files:
      - ./prod.env

bases:
  - ../base
